language: python

python:
    - "2.7"

env:
    - DJANGO=1_3
    - DJANGO=1_4
    - DJANGO=1_5
    - DJANGO=1_6
    - DJANGO=1_0

install: "pip install -r test-projects/setup.pip -r test-projects/django$(DJANGO)/setup.pip"

script: "cd test-projects/django$(DJANGO) && python manage.py test slumber_examples"
